- hosts: tag_callparty-prod
  user: ubuntu
  sudo: true

  tasks:

    - include_vars: vars.yml
      tags:
        - quick

    - include_vars: prod_vars.yml
      tags:
        - quick

    - include: deploy_tasks.yml


  handlers:

    - name: restart nginx
      action: service name=nginx state=restarted