- hosts: tag_callparty-prod
  user: ubuntu
  sudo: True

  tasks:
    - include_vars: vars.yml
    - include_vars: prod_vars.yml
    - include: deploy_tasks.yml

  handlers:

    - name: restart nginx
      action: service name=nginx state=restarted