  - name: add nginx ppa
    action: apt_repository repo=ppa:nginx/stable state=present

  - name: add certbot ppa
    apt_repository:
      repo: ppa:certbot/certbot
      state: present

  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - nodejs-legacy
      - git
      - mcrypt
      - nginx
      - curl
      - certbot

  - name: install nvm
    git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version=v0.32.1
    become: yes
    become_user: ubuntu

  - name: source nvm in ~/.profile
    lineinfile: dest=~/.profile line="source ~/.nvm/nvm.sh" create=yes
    become: yes
    become_user: ubuntu

  - name: install node version 7.6.0
    command: sudo -iu ubuntu nvm install v7.6.0

  - name: set default node version to 7.6.0
    command: sudo -iu ubuntu nvm alias default v7.6.0

  - name: create symlink from nvm node to /usr/local/bin/node
    file: src=/home/ubuntu/.nvm/versions/node/v7.6.0/bin/{{item}} dest=/usr/local/bin/{{item}} state=link
    with_items:
      - node
      - npm

  - name: remove default nginx site
    action: file path={{item}} state=absent
    with_items:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available/default

  - name: write nginx.conf
    action: template src=templates/nginx.conf dest=/etc/nginx/nginx.conf

  - name: write nginx default conf
    template: src=templates/nginx_default.conf dest=/etc/nginx/sites-available/default

  - name: restart nginx
    service: name=nginx state=restarted

  - name: Install pm2
    npm: name=pm2 global=yes production=yes
    sudo: yes

  - name: ensure config directory
    action: file dest={{config_dir}} state=directory

  - name: Copy pm2.json file
    action: template src=templates/pm2.json dest={{config_dir}}/pm2.json

  - name: create webgroup if it doesn't exist
    group: name=webgroup state=present

  - name: ensure ubuntu belongs to webgroup
    user: name=ubuntu groups=webgroup append=yes

  - name: copy over ssh keys for deploy purposes
    action: copy src={{item.from}} dest={{item.to}} mode={{item.mode}}
    with_items:
      - { from: 'secret_files/deploy_rsa.pub', to: '/root/.ssh/id_rsa.pub', mode: '0644' }
      - { from: 'secret_files/deploy_rsa', to: '/root/.ssh/id_rsa', mode: '0600' }

  - name: obtain or renew cert for domain from Let's Encrypt
    command: certbot certonly --text -n --no-self-upgrade -m hi@callparty.org -d admin.callparty.org,staging.callparty.org --agree-tos --webroot -w /usr/share/nginx/html --expand --allow-subset-of-names

  - name: create cron job for auto renewing Let's Encrypt cert
    cron: name="renew letsencrypt cert" hour="2,11" minute=0 job="certbot renew --quiet --no-self-upgrade; sudo service nginx restart"
