repo_branch: master
nginx_crt: secret_files/staging.callparty.org_nginx.crt
nginx_key: secret_files/staging.callparty.org_nginx.key
node_env: secret_files/staging_env
domain_name: staging.callparty.org