- hosts: tag_callparty-staging
  become: yes
  become_user: root

  tasks:

    - include_vars: vars.yml
      tags:
        - quick

    - include_vars: staging_vars.yml
      tags:
        - quick

    - include: deploy_tasks.yml


  handlers:

    - name: restart nginx
      action: service name=nginx state=restarted