dist: trusty
sudo: required

language: node_js

python: "2.7"

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-trusty
    packages:
    - mongodb-org-server

branches:
  only:
    - master
    - staging
    - prod

install:
  - cd $TRAVIS_BUILD_DIR/backend && npm install
  - cd $TRAVIS_BUILD_DIR/frontend && npm install

script:
  - cd $TRAVIS_BUILD_DIR/backend && eslint .
  - cd $TRAVIS_BUILD_DIR/backend && npm test
  - cd $TRAVIS_BUILD_DIR/frontend && eslint .
  - cd $TRAVIS_BUILD_DIR/frontend && npm test

before_deploy:
  - sudo apt-get install python-dev -y
  - cd $TRAVIS_BUILD_DIR/backend && pip install -r requirements.txt
  - cd $TRAVIS_BUILD_DIR/frontend && npm install && cd $TRAVIS_BUILD_DIR
  - openssl aes-256-cbc -K $encrypted_5d10786c9aae_key -iv $encrypted_5d10786c9aae_iv -in backend/devops/secret_files.tar.enc -out backend/devops/secret_files.tar -d
  - cd $TRAVIS_BUILD_DIR/backend/devops && tar xvf secret_files.tar && cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    script: backend/bash/staging_deploy.sh
    skip_cleanup: true
    on:
      branch: staging

  - provider: script
    script: backend/bash/prod_deploy.sh
    skip_cleanup: true
    on:
      branch: prod
