language: node_js

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

branches:
  only:
    - master

env:
  - TEST_DIR=backend
  - TEST_DIR=frontend

before_install: cd $TEST_DIR

script:
  - eslint .
  - npm test
