language: node_js

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

branches:
  only:
    - master
    - staging
    - prod

before_install:
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -q
  - sudo apt-get install ansible

install:
  - cd $TRAVIS_BUILD_DIR/backend && npm install
  - cd $TRAVIS_BUILD_DIR/frontend && npm install

script:
  - cd $TRAVIS_BUILD_DIR/backend && eslint .
  - cd $TRAVIS_BUILD_DIR/backend && npm test
  - cd $TRAVIS_BUILD_DIR/frontend && eslint .
  - cd $TRAVIS_BUILD_DIR/frontend && npm test

before_deploy: cd $TRAVIS_BUILD_DIR/frontend && npm install && cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    script: backend/bash/staging_quick_deploy.sh
    skip_cleanup: true
    on:
      branch: staging

  - provider: script
    script: backend/bash/prod_deploy.sh
    skip_cleanup: true
    on:
      branch: prod
