language: node_js

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

branches:
  only:
    - master
    - staging
    - prod

env:
  - TEST_DIR=backend
  - TEST_DIR=frontend

before_install: cd $TEST_DIR

script:
  - eslint .
  - npm test

before_deploy: cd $TRAVIS_BUILD_DIR/frontend && npm install && cd $TRAVIS_BUILD_DIR

deploy:
  - provider: script
    script: backend/bash/staging_quick_deploy.sh
    on:
      branch: staging

  - provider: script
    script: backend/bash/prod_deploy.sh
    on:
      branch: prod
